/**
 * Swagger Maven Plugin Sample
 * This is a sample.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Topo } from './topo';
import { User } from './user';


export interface UserMessage {
    id?: number;
    user?: User;
    topo?: Topo;
    message?: string;
    date?: Date;
}
